# Generated by Django 2.0.6 on 2018-06-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
