# Generated by Django 2.0.6 on 2018-06-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
