# Generated by Django 2.0.6 on 2018-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180621_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='travel_date',
            field=models.DateField(verbose_name='Post travel date'),
        ),
    ]
