# Generated by Django 2.0.6 on 2018-06-21 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180621_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post travel date'),
        ),
    ]
